### ISSUE TITLE
No reducer provided for key "XXX"

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/haztrak#319]
# 🐞 Bug Report

This one is driving me a little nuts, 

When running tests for the browser client, we consistently get this console.error

```typescript
  console.error
    No reducer provided for key "user"

      4 | import userReducers, { login } from 'store/userSlice';
      5 |
    > 6 | const rootReducer = combineReducers({
        |                                    ^
      7 |   user: userReducers,
      8 |   notification: notificationReducers,
      9 |   rcraProfile: rcraProfileReducers,

      at warning (node_modules/redux/lib/redux.js:434:13)
      at combineReducers (node_modules/redux/lib/redux.js:518:9)
      at Object.<anonymous> (src/store/rootStore.ts:6:36)
      at Object.<anonymous> (src/services/HtApi.ts:5:1)
      at Object.<anonymous> (src/services/index.ts:1:1)
      at Object.<anonymous> (src/store/userSlice/user.slice.ts:2:1)
      at Object.<anonymous> (src/store/userSlice/index.ts:1:1)
      at Object.<anonymous> (src/store/userSlice/user.spec.ts:3:1)
```

We also get one for the `rcraProfileReducers` but not the `notificationReducers`. 

It's not causing any problems, we don't see any errors during development in the console, only as a warning during tests. However it's kinda bugging me. 

[This StackOverflow question](https://stackoverflow.com/questions/44791528/react-redux-no-reducer-provided-for-key-coins) suggests that it is likely a circular import. However I cannot (or haven't been bothered) to figure out what is causing the warning.

**Comment by dpgraham4401** [comment]
Ok, now that I'm looking at it, I see. 

It's because we're importing the store (rootStore) in the htApi service. which is used in the `rcraProfileSlice` and `userSlice`s
